# @name mintOmuzeoItems
POST http://localhost:3000/create HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="receiver"

0x154880e843e25e08
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

dog
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="contract"

OmuzeoItems
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="1.jpg"
Content-Type: image/jpeg

< ./public/assets/1.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name mintOmuzeoNFT
POST http://localhost:3000/create HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="creator"

0x154880e843e25e08
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

dog
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="contract"

OmuzeoNFT
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="5.jpg"
Content-Type: image/jpeg

< ./public/assets/5.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
