version: "3"
services:
# TODO: figure out how to make the dockerised web hot reloadable
#    web:
#        container_name: "web"
#        build:
#            context: .
#            dockerfile: Dockerfile.web
#        environment:
#            - CHOKIDAR_USEPOLLING=true
#        ports:
#            - "3000:3000"
    wallet:
        build:
            context: .
            dockerfile: Dockerfile.wallet
        ports:
            - "8701:8701"
        environment:
            - PORT=8701
            - FLOW_ACCESS_NODE=http://emulator:8080
            - FLOW_ACCOUNT_KEY_ID=0
            - FLOW_ACCOUNT_PRIVATE_KEY=7fe7e14da2973c23841123aa772f3b0a1ba4752b50d9ecce81171f50f0439b7b
            - FLOW_ACCOUNT_PUBLIC_KEY=46660d0f5c490d238426016b95e1351508202b4fc41fad1aa6ffa50608ae2f6e5fd9731d58e205d240d009ee7a73fdff1606119650c247ff5ebd7727bfc0931f
            - FLOW_INIT_ACCOUNTS=0
            - FLOW_ACCOUNT_ADDRESS=0xf8d6e0586b0a20c7
            - FLOW_AVATAR_URL=https://avatars.onflow.org/avatar/
    emulator:
        image: gcr.io/flow-container-registry/emulator:0.20.2
        ports:
            - "8080:8080"
            - "3569:3569"
        environment:
            - FLOW_SERVICEPRIVATEKEY=7fe7e14da2973c23841123aa772f3b0a1ba4752b50d9ecce81171f50f0439b7b
            - FLOW_SERVICEKEYSIGALGO=ECDSA_P256
            - FLOW_SERVICEKEYHASHALGO=SHA3_256
